applied shellshock to scripts

diff --git a/blacklist b/blacklist
--- a/blacklist
+++ b/blacklist
@@ -1,8 +1,8 @@
 #!/bin/sh
-
+# shellcheck disable=SC2039
 usage () {
 	cat <<EOM
-Usage:	$app [OPTION]... [COMMAND] [arguments...]
+Usage:	$BKL_APP [OPTION]... [COMMAND] [arguments...]
 	
 Commands:
 		
@@ -31,13 +31,13 @@ Options:
 EOM
 	exit 0
 }
-green_text(){ [[ "$bkl_color" == "always" ]] && echo -e "\e[32m$*\e[0m" || echo "$*"; }
-red_text(){ [[ "$bkl_color" != "no" ]] && echo -e "\e[31m$*\e[0m" || echo "$*";}
-yellow_text(){ [[ "$bkl_color" == "always" ]] && echo -e "\e[33m$*\e[0m" || echo "$*"; }
-echo_std(){ echo "${bkl_app}: $*"; }
-echo_ok(){ echo "${bkl_app}: $(green_text [OK]) $*"; }
-echo_error(){ [[ $bkl_verbose -eq 0 ]] && >&2 echo "${bkl_app}: $(red_text [ERROR]) $1"; }
-echo_warning(){ [[ $bkl_verbose -eq 0 ]] && >&2 echo "${bkl_app}: $(yellow_text [WARNING]) $1"; }
+green_text(){ [[ "$BKL_COLOR" == "always" ]] && echo -e "\e[32m$*\e[0m" || echo "$*"; }
+red_text(){ [[ "$BKL_COLOR" != "no" ]] && echo -e "\e[31m$*\e[0m" || echo "$*";}
+yellow_text(){ [[ "$BKL_COLOR" == "always" ]] && echo -e "\e[33m$*\e[0m" || echo "$*"; }
+echo_std(){ echo "${BKL_APP}: $*"; }
+echo_ok(){ echo "${BKL_APP}: $(green_text [OK]) $*"; }
+echo_error(){ [[ $BKL_VERBOSE -eq 0 ]] && >&2 echo "${BKL_APP}: $(red_text [ERROR]) $1"; }
+echo_warning(){ [[ $BKL_VERBOSE -eq 0 ]] && >&2 echo "${BKL_APP}: $(yellow_text [WARNING]) $1"; }
 
 #called inside getopts with varname opt
 arg_required() {
@@ -57,11 +57,10 @@ is_installed(){ type "$1" >/dev/null; }
 install_checks ()  {
 	is_installed "uci" || { echo "uci not found. Cannot proceed."; exit 1; }
 	if [[ "$1" == "sip" || "$1" == "pjsip" ]]; then
-		is_installed "/usr/bin/$app" && 
-		{ echo_error "$app: already installed. Uninstall with --keep first."
+		is_installed "/usr/bin/$BKL_APP" && 
+		{ echo_error "$BKL_APP: already installed. Uninstall with --keep first."
 		exit 1; }
-		is_installed "asterisk"
-		if [[ "$blk_interactive" -eq 0 && "$?" -eq 0 ]]; then
+		if is_installed "asterisk" && [[ "$BKL_INTERACTIVE" -eq 0 ]]; then
 			read  -n 1 -sp "asterisk already installed. Do you wish to continue [y/N] " cnt
 			[[ "$cnt" == "y" || "$cnt" == "Y" ]] || exit 0
 		fi
@@ -73,11 +72,9 @@ install_checks ()  {
 uninstall_export () {
 	echo_warning "You will lose your database."
 	read -n 1 -sp "Export the database before continue [y/N] " cnt
-	[[ "$cnt" == "y" || "$cnt" == "Y" ]] && 
-	{ echo "blacklist:" >> blacklist.export; 
-	export_db "blacklist" >> blacklist.export; 
-	echo "whitelist:" >> blacklist.export;
-	export_db "whitelist" >> blacklist.export; }
+	[[ "$cnt" == "y" || "$cnt" == "Y" ]] &&
+	{ echo "blacklist:"; export_db "blacklist"; echo "whitelist:";
+	export_db "whitelist"; } >> blacklist.export 
 	return 0
 }
 export_db () {
@@ -106,7 +103,7 @@ database_insert () {
 			done
 	else
 		#from user assume it's a phone number, but still check input
-		local test=$(echo $user_input | grep -oE "\+?[0-9]+")
+		local test; test=$(echo "$user_input" | grep -oE "\+?[0-9]+")
 		if [[ "${test}" != "$user_input" ]];  then
 			echo_std "$user_input: not a valid number. " && exit 1
 		else
@@ -116,6 +113,7 @@ database_insert () {
 
 }
 parse_args () {
+	# shellcheck disable=SC2214
 	while getopts ":hsVwm:l:N-:" opt; do
 		if [[ "$opt" = "-" ]]; then   # long option: reformulate opt and OPTARG
 			opt="${OPTARG%%=*}"       # extract long option name
@@ -124,17 +122,17 @@ parse_args () {
 		fi
 		case "${opt}" in
 			h | help)			usage;;
-			s | suppress-error)	bkl_verbose=1;;
-			V | version) 		echo "$bkl_app $bkl_version"; exit 0;;
-			no-cdr) 			bkl_nocdr=0;;
+			s | suppress-error)	BKL_VERBOSE=1;;
+			V | version) 		echo "$BKL_APP $BKL_VERSION"; exit 0;;
+			no-cdr) 			BKL_NOCDR=0;;
 			w | whitelist) 		db="whitelist";;
 			l | location)		arg_required && valid_location "${OPTARG}" &&
-								bkl_location="${OPTARG}";;
+								BKL_LOCATION="${OPTARG}";;
 			color) 				arg_required && is_color_opt "${OPTARG}" && 
-								bkl_color="${OPTARG}";;
+								BKL_COLOR="${OPTARG}";;
 			csv)				csv=0;;
-			keep)				blk_keep_folder=0;;
-			N | no-interactive)	blk_interactive=1;bkl_verbose=1;;
+			keep)				BKL_KEEP_FOLDER=0;;
+			N | no-interactive)	BKL_INTERACTIVE=1;BKL_VERBOSE=1;;
 			m | min-digits)		arg_required && is_digit "${OPTARG}" &&
 								min_digits="${OPTARG}";;
 			# bad long option
@@ -148,10 +146,10 @@ parse_args () {
 	[[ -n "$command" ]] && shift
 	case "$command" in
 		install) 	install_checks "$1" && #$1 is either sip or pjsip
-					export blk_driver="$1" && ./install
+					export BKL_DRIVER="$1" && ./install
 					shift;;
-		uninstall) 	[[ "$blk_interactive" -eq 0 ]] && uninstall_export
-					"${installed_location}/uninstall";;
+		uninstall) 	[[ "$BKL_INTERACTIVE" -eq 0 ]] && uninstall_export
+					"${installed_location}/uninstall" "$installed_location";;
 		block)		database_op "blacklist" "$1"
 					shift;;
 		whitelist) 	database_insert "whitelist" "$1"# ""
@@ -167,21 +165,21 @@ parse_args () {
 
 main() {
 	# 0 is true in bash
-	export bkl_app="blacklist"
-	export bkl_version="4.0.5b"
-	export bkl_color="auto"
+	export BKL_APP="blacklist"
+	export BKL_VERSION="4.1.12-alpha"
+	export BKL_COLOR="auto"
 	[[ $# -eq 0 ]] && usage
-	export bkl_verbose=0
-	export bkl_nocdr=1	
-	export bkl_location="/usr/share"
-	export blk_keep_folder=1
-	export blk_interactive=0
+	export BKL_VERBOSE=0
+	export BKL_NOCDR=1	
+	export BKL_LOCATION="/usr/share"
+	export BKL_KEEP_FOLDER=1
+	export BKL_INTERACTIVE=0
 	local installed_location=__data_directory__
 	local csv=1
 	local db="blacklist"
 	local min_digits=7
 	parse_args "$@"
-	local model="$(uci get env.var.prod_friendly_name)"
+	local model; model="$(uci get env.var.prod_friendly_name)"
 	[[ "$model" != "DGA4132" ]] && echo_warning "This script was tested only on DGA4132!"
 }
 main "$@"
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,28 +1,27 @@
-#!/bin/sh
+#!/bin/bash
 ###########################################################
 ##
 ##Blacklist install script
 ##Call this with: blacklist [OPTION]... install pjsip|sip
 ##
 ##########################################################
-green_text(){ [[ "$bkl_color" == "always" ]] && echo -e "\e[32m$*\e[0m" || echo "$*"; }
-red_text(){ [[ "$bkl_color" != "no" ]] && echo -e "\e[31m$*\e[0m" || echo "$*";}
-yellow_text(){ [[ "$bkl_color" == "always" ]] && echo -e "\e[33m$*\e[0m" || echo "$*"; }
-echo_std(){ echo "${bkl_app}: $*"; }
-echo_ok(){ echo "${bkl_app}: $(green_text [OK]) $*"; }
-echo_error(){ [[ $bkl_verbose -eq 0 ]] && >&2 echo "${bkl_app}: $(red_text [ERROR]) $1"; }
-echo_warning(){ [[ $bkl_verbose -eq 0 ]] && >&2 echo "${bkl_app}: $(yellow_text [WARNING]) $1"; }
+green_text(){ [[ "$BKL_COLOR" == "always" ]] && echo -e "\e[32m$*\e[0m" || echo "$*"; }
+red_text(){ [[ "$BKL_COLOR" != "no" ]] && echo -e "\e[31m$*\e[0m" || echo "$*";}
+yellow_text(){ [[ "$BKL_COLOR" == "always" ]] && echo -e "\e[33m$*\e[0m" || echo "$*"; }
+echo_std(){ echo "${BKL_APP}: $*"; }
+echo_ok(){ echo "${BKL_APP}: $(green_text [OK]) $*"; }
+echo_error(){ [[ $BKL_VERBOSE -eq 0 ]] && >&2 echo "${BKL_APP}: $(red_text [ERROR]) $1"; }
+echo_warning(){ [[ $BKL_VERBOSE -eq 0 ]] && >&2 echo "${BKL_APP}: $(yellow_text [WARNING]) $1"; }
 
 copy_configs_and_blacklist() {
-  [[ ! -d "${bkl_location}/blacklist" ]] && mkdir "${bkl_location}/blacklist"
+  [[ ! -d "${BKL_LOCATION}/blacklist" ]] && mkdir "${BKL_LOCATION}/blacklist"
 	chmod u+x ./blacklist
 	cp ./blacklist /usr/bin
-	cp -r . "${bkl_location}/blacklist"
-	cp -r "${bkl_driver}_chan"/. "${ast_etc_dir}"
+	cp -r . "${BKL_LOCATION}/blacklist"
+	cp -r "${BKL_DRIVER}_chan"/. "${ast_etc_dir}"
   #set blacklist dir in uninstall script
-  sed -i "s:__data_directory__:${bkl_location}/blacklist:" "${bkl_location}/blacklist/uninstall"
-  sed -i "s:__data_directory__:${bkl_location}/blacklist:" "/usr/bin/blacklist" 
-  local ast_agi_dir=$(grep astagidir "${ast_etc_dir}/asterisk.conf" | cut -d " " -f3)
+  sed -i "s:__data_directory__:${BKL_LOCATION}/blacklist:" "/usr/bin/blacklist" 
+  local ast_agi_dir; ast_agi_dir=$(grep astagidir "${ast_etc_dir}/asterisk.conf" | cut -d " " -f3)
   if [[ ! -d "${ast_agi_dir}" ]]; then
 		mkdir "${ast_agi_dir}"
   fi
@@ -35,8 +34,9 @@ select_profile(){
   local indexes=""
   for i in $(seq 0 5);do
     #local eats the exit code
-    local enabled; enabled=$(uci -q get mmpbxrvsipnet.sip_profile_$i.enabled)|| break
-    local net=$(uci -q get mmpbxrvsipnet.sip_profile_$i.network)
+    local enabled net 
+    enabled=$(uci -q get mmpbxrvsipnet.sip_profile_"$i".enabled)|| break
+    net=$(uci -q get mmpbxrvsipnet.sip_profile_"$i".network)
     if [[ "$enabled" -eq 1 && "$net" == "sip_net" ]]; then
       count_profile=$((count_profile + 1))
       indexes="$indexes $i"
@@ -52,16 +52,16 @@ select_profile(){
     #alternative to xargs -i
     print_uri() {
       while [[ "$#" -gt 0 ]]; do
-        echo "$1: $(uci -q get mmpbxrvsipnet.sip_profile_$1.uri)"
+        echo "$1: $(uci -q get mmpbxrvsipnet.sip_profile_"$1".uri)"
         shift
       done
     }
-    if [[ "$blk_interactive" -eq 0 ]]; then
-      read -n1 -sp "Multiple profiles available: select [$indexes]"$'\n'"$(print_uri $indexes)"$'\n' ind
+    if [[ "$BKL_INTERACTIVE" -eq 0 ]]; then
+      read -n1 -sp "Multiple profiles available: select [$indexes]"$'\n'"$(print_uri "$indexes")"$'\n' ind
       [[ "$ind" -ge 0 && "$ind" -lt "$count_profile" ]] && echo "$ind" || 
       { echo_error "Invalid profile. Cannot config mmpbx, aborting"; exit 1; }
     else
-      echo ${indexes:0:1} #non interactive picks first choice
+      echo "${indexes:0:1}" #non interactive picks first choice
     fi
   fi
 }
@@ -70,16 +70,17 @@ config_mmpbx() {
 	if [[ -f /etc/config/mmpbxrvsipnet.orig ]]; then
 		cp /etc/config/mmpbxrvsipnet.orig /etc/config/mmpbxrvsipnet
   fi
-  local profile_idx=$(select_profile)
-  local secret=$(uci get mmpbxrvsipnet.sip_profile_$profile_idx.password)
-  local uri=$(uci get mmpbxrvsipnet.sip_profile_$profile_idx.uri)
-  local username=$(uci get mmpbxrvsipnet.sip_profile_$profile_idx.user_name)    
-  local primary_proxy=$(uci get mmpbxrvsipnet.sip_net.primary_proxy)
-  local port=$(uci get mmpbxrvsipnet.sip_net.primary_registrar_port)
-  local domain=$(uci get mmpbxrvsipnet.sip_net.domain_name)
+  local profile_idx secret uri username primary_proxy port domain
+  profile_idx=$(select_profile)
+  secret=$(uci get mmpbxrvsipnet.sip_profile_"$profile_idx".password)
+  uri=$(uci get mmpbxrvsipnet.sip_profile_"$profile_idx".uri)
+  username=$(uci get mmpbxrvsipnet.sip_profile_"$profile_idx".user_name)    
+  primary_proxy=$(uci get mmpbxrvsipnet.sip_net.primary_proxy)
+  port=$(uci get mmpbxrvsipnet.sip_net.primary_registrar_port)
+  domain=$(uci get mmpbxrvsipnet.sip_net.domain_name)
   sed -i "s/URI/${uri}/g;s/USERNAME/${username}/g;
 	s/SECRET/${secret}/g;s/PRIMARY_PROXY/${primary_proxy}/g;
-  s/DOMAIN/${domain}/g;s/PORT/${port}/g" "${ast_etc_dir}/${bkl_driver}.conf"
+  s/DOMAIN/${domain}/g;s/PORT/${port}/g" "${ast_etc_dir}/${BKL_DRIVER}.conf"
   sed -i "s/URI/${uri}/g" "${ast_etc_dir}/extensions.conf"
   if [[ ! -f /etc/config/mmpbxrvsipnet.orig ]]; then
 		cp /etc/config/mmpbxrvsipnet /etc/config/mmpbxrvsipnet.orig
@@ -108,15 +109,15 @@ is_asterisk_enabled () {
 	echo_error "Failed to start Asterisk daemon. Aborting." && exit 1
 }
 opkg_install_asterisk () {
-  local ov=$([[ "$bkl_verbose" -eq 0 ]] && echo "-V1" || echo "-V0")
+  local ov; ov=$([[ "$BKL_VERBOSE" -eq 0 ]] && echo "-V1" || echo "-V0")
   opkg update
   opkg "$ov" install asterisk"${ast_short}"
   opkg "$ov" install asterisk"${ast_short}"-app-system
   opkg "$ov" install asterisk"${ast_short}"-res-agi
-  if [[ "$bkl_driver" == "pjsip" ]]; then
-    opkg "$ov" install asterisk"${ast_short}"-"${bkl_driver}"
+  if [[ "$BKL_DRIVER" == "pjsip" ]]; then
+    opkg "$ov" install asterisk"${ast_short}"-"${BKL_DRIVER}"
   else
-    opkg "$ov" install asterisk"${ast_short}"-chan-"${bkl_driver}"
+    opkg "$ov" install asterisk"${ast_short}"-chan-"${BKL_DRIVER}"
   fi
   opkg "$ov" install asterisk"${ast_short}"-res-rtp-asterisk
   opkg "$ov" install asterisk"${ast_short}"-format-pcm
@@ -131,7 +132,7 @@ opkg_install_asterisk () {
 	opkg "$ov" install asterisk"${ast_short}"-bridge-simple
 	opkg "$ov" install asterisk"${ast_short}"-bridge-softmix 
 	#Cdr?
-	if [[ "$bkl_nocdr" -eq 1 ]]; then
+	if [[ -n "$BKL_NOCDR" && "$BKL_NOCDR" -eq 1 ]]; then
     opkg "$ov" install asterisk"${ast_short}"-cdr
 		opkg "$ov" install asterisk"${ast_short}"-cdr-csv
 	fi
@@ -163,7 +164,7 @@ verify_contacts () {
   while [[ "${retry}" -gt 0 ]]; do
   if ! op; then
 		echo_warning "Not all contacts are reachable"
-		retry=$(( ${retry} - 1 ))
+		retry=$((retry - 1))
     helper_verify_aor tel || continue
     helper_verify_aor "${URI}" || continue
   else
@@ -196,7 +197,7 @@ verify_registration () {
 main () {
   #Change this to install another version of asterisk
   local ast_ver="13.20.0"
-  [[ -z "$blk_app" ]] && { echo_error "Launch with blacklist!" && exit 1; }
+  [[ -z "$BKL_APP" ]] && { echo_error "Launch with blacklist!" && exit 1; }
   if pgrep asterisk > /dev/null; then
     /etc/init.d/asterisk stop
   fi
@@ -207,7 +208,7 @@ main () {
   echo_std "Installing Asterisk..."
   local ast_short="${ast_ver:0:2}"
 	opkg_install_asterisk
-  local inst_ver=$(asterisk -V | cut -d " " -f 2)
+  local inst_ver; inst_ver=$(asterisk -V | cut -d " " -f 2)
   if [[ "${inst_ver}" != "${ast_ver}" ]]; then
 		echo_error "Incorrect Asterisk version."
 	  uninstall_asterisk "${inst_ver}"
@@ -233,10 +234,10 @@ main () {
   echo_std "Enabling Asterisk daemon..."
   /etc/init.d/asterisk enable
 	time_stamp=$(date +'%b %d %H')
-  [[ ${time_stamp:4:1} -eq 0 ]] && time_stamp=$(echo $time_stamp | sed "s/0/ /")
+  [[ ${time_stamp:4:1} -eq 0 ]] && time_stamp=$(echo "$time_stamp" | sed "s/0/ /")
   is_asterisk_enabled  
 	#for pjsip driver, TODO sip
-  if [[ "$bkl_driver" == "pjsip" ]]; then
+  if [[ "$BKL_DRIVER" == "pjsip" ]]; then
     verify_registration && verify_contacts
     if [[ "$?" -eq 1 ]] ;then 
 		  echo_error "Failed to configure the asterisk setup."
